# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b17f894e80ea073ba3ee2de9c0bdd8646bd20c4104c37badc6699fb88cd3dda497c7faab5209275ef7870f0947a9c392c6bfb24ea375545e93d669b60c00baa

test:
  secret_key_base: 5e58926d4d0398f6f8563b51616606f441c2a81502bd1b746977f903c2f7996374ad35358eca0cb0bcdf83843eec06fb620132aa1381dfcf026b5b1fabf617e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
